name: 'Parse event comment body'
description: 'Parse body'

inputs:
  BODY:
    description: 'Input body to parse'
    required: true
runs:
  using: composite
  steps:
    - name: Parse
      shell: bash
      run: echo $BODY
      env:
        BODY: ${{ inputs.body }}
